
import javax.swing.JOptionPane;

public class Menu extends javax.swing.JFrame {
    General General1 = new Dama();
    General General2 = new Caballero();
    General General3 = new Niño();
    
    /*public void opcion(){
    int op;
    op = Integer.parseInt(Codigo.getText());
}
    /**
     * Creates new form Menu
     */
    public Menu() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Binfo = new javax.swing.JButton();
        Binventario = new javax.swing.JButton();
        Bretirar = new javax.swing.JButton();
        Bingresar = new javax.swing.JButton();
        Clean = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        Codigo = new javax.swing.JTextField();
        IngreReti = new javax.swing.JTextField();
        Respuesta = new javax.swing.JTextField();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        Binfo.setText("Datos");
        Binfo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BinfoActionPerformed(evt);
            }
        });

        Binventario.setText("inventario");
        Binventario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BinventarioActionPerformed(evt);
            }
        });

        Bretirar.setText("Retirar");
        Bretirar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BretirarActionPerformed(evt);
            }
        });

        Bingresar.setText("Ingresar");
        Bingresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BingresarActionPerformed(evt);
            }
        });

        Clean.setText("Clean");
        Clean.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CleanActionPerformed(evt);
            }
        });

        jLabel1.setForeground(new java.awt.Color(0, 0, 255));
        jLabel1.setText("Ingresar codigo a buscar");

        Codigo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CodigoActionPerformed(evt);
            }
        });

        IngreReti.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                IngreRetiActionPerformed(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(0, 0, 255));
        jPanel1.setForeground(new java.awt.Color(0, 0, 204));

        jLabel2.setBackground(new java.awt.Color(255, 255, 255));
        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Zapateria Style");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 179, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel2)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(Codigo, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(414, 414, 414)
                                .addComponent(IngreReti, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(25, 25, 25)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(Binventario)
                                .addGap(18, 18, 18)
                                .addComponent(Bretirar))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(Binfo, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(Bingresar, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(Clean)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 12, Short.MAX_VALUE)
                .addComponent(Respuesta, javax.swing.GroupLayout.PREFERRED_SIZE, 330, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(145, 145, 145))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(Codigo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(29, 29, 29)
                        .addComponent(Respuesta, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(IngreReti, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(64, 64, 64)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Binfo)
                            .addComponent(Bingresar))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 14, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Binventario)
                            .addComponent(Bretirar)
                            .addComponent(Clean))
                        .addGap(33, 33, 33))))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BingresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BingresarActionPerformed
        // TODO add your handling code here:
        Bingresar.setEnabled(false);

        Binfo.setVisible(false);
        Bretirar.setVisible(false);
        Binventario.setVisible(false);
        IngreReti.setVisible(false);
        String CodigoText = Codigo.getText();
        String ingretiText = Ingreti.getText();
        
        if (!CodigoText.isEmpty() && !ingretiText.isEmpty()) {
    try {
        int op = Integer.parseInt(Codigo.getText());
        int can = Integer.parseInt(Ingreti.getText());
        int canDama= General1.cantidad() + can;
        int canCaballero =  General2.cantidad() + can;
        int canNino = General3.cantidad() + can;
        // TODO add your handling code here:
       switch(op){
    case 1:
        General1.agregarCantidad(can);
        Respuesta.setText("Ha elegido ingresar cantidad a Dama\nCantidad disponible: \"" + General1.cantidad());
        break;
    case 2:
        General2.agregarCantidad(can);
        Respuesta.setText("Ha elegido ingresar cantidad a Caballero\nCantidad disponible: \"" + General2.cantidad());
        break;
    case 3:
        General3.agregarCantidad(can);
        Respuesta.setText("Ha elegido ingresar cantidad a niños\nCantidad disponible: \"" + General3.cantidad());
        break;
}

        } catch (NumberFormatException e) {
        // Manejo del caso cuando el campo de entrada no es un número
        Respuesta.setText("Por favor, ingrese un número válido.");
    }
} else {
    // Manejo del caso cuando el campo de entrada está vacío
    Respuesta.setText("Por favor, no deje los campos vacíos.");
        }
    }//GEN-LAST:event_BingresarActionPerformed

    private void CodigoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CodigoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CodigoActionPerformed

    private void BretirarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BretirarActionPerformed
        // TODO add your handling code here:
        Bretirar.setEnabled(false);
        Bingresar.setVisible(false);
        Binfo.setVisible(false);
        Binventario.setVisible(false);
        IngreReti.setVisible(false);
         
        int op;
        op = Integer.parseInt(Codigo.getText());
        int can;
        can = Integer.parseInt(IngreReti.getText());
        int canDama= General1.cantidad() - can;
        int canCaballero =  General2.cantidad() - can;
        int canNino = General3.cantidad() - can;
        // TODO add your handling code here:
        switch(op){
            case 001 : 
                Respuesta.setText( """
                                                    Ha elegido retirar cantidad a  Dama
                                                    Cantidad disponible: """ + canDama);
                break;
            case 002 :
                Respuesta.setText( """
                                                    Ha elegido retirar cantidad a Caballero
                                                    Cantidad disponible: """ + canCaballero);
                break;
            case 003 : 
                Respuesta.setText( """
                                                    Ha elegido retirar cantidad a niños
                                                    Cantidad disponible: """  + canNino);
                break;
        }
        
    }//GEN-LAST:event_BretirarActionPerformed

    private void BinfoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BinfoActionPerformed
        Binventario.setVisible(false);
        Bingresar.setVisible(false);
        Bretirar.setVisible(false);
        Binfo.setEnabled(false);
        
        
        int op;
        op = Integer.parseInt(Codigo.getText());
        switch(op){

            case 001 : 
                Respuesta.setText ("Informacion de Caballero" + General2.marca() + General2.Color() + General2.talla() + General2.ubicacion() + General2.codigo());

                break;
            case 002 :
                Respuesta.setText ("Informacion de Dama" + General1.marca() + General1.Color() + General1.talla() + General1.ubicacion() + General1.codigo());
                break;
            case 003 : 
                Respuesta.setText ("Informacion de Niño" + General3.marca() + General3.Color() + General3.talla() + General3.ubicacion() + General3.codigo());

                break;
        }  
    }//GEN-LAST:event_BinfoActionPerformed

    private void IngreRetiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_IngreRetiActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_IngreRetiActionPerformed

    private void BinventarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BinventarioActionPerformed
        // TODO add your handling code here:
        Binventario.setEnabled(false);

        Bingresar.setVisible(false);
        Bretirar.setVisible(false);
        Binfo.setVisible(false);
        IngreReti.setVisible(false);
        
        int op;
        op = Integer.parseInt(Codigo.getText());
        switch(op){

            case 001 : 
                Respuesta.setText ("Inventario de Caballero" + General2.cantidad());
                break;
            case 002 :
                Respuesta.setText ("Inventario de Dama" + General1.cantidad());
                break;
            case 003 : 
                Respuesta.setText ("Inventario de Niño" + General3.cantidad());

                break;
        }
    }//GEN-LAST:event_BinventarioActionPerformed

    private void CleanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CleanActionPerformed
        // TODO add your handling code here:
        IngreReti.setText(" ");
        //Codigo.setText(" ");
        IngreReti.setVisible(true);
        Binfo.setVisible(true);
        Bretirar.setVisible(true);
        Binventario.setVisible(true);
        Bingresar.setVisible(true);
        Binfo.setEnabled(true);
        Binventario.setEnabled(true);
        Bingresar.setEnabled(true);
        Bretirar.setEnabled(true);



        
    }//GEN-LAST:event_CleanActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Menu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Binfo;
    private javax.swing.JButton Bingresar;
    private javax.swing.JButton Binventario;
    private javax.swing.JButton Bretirar;
    private javax.swing.JButton Clean;
    private javax.swing.JTextField Codigo;
    private javax.swing.JTextField IngreReti;
    private javax.swing.JTextField Respuesta;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables

    private static class Ingreti {

        private static String getText() {
            throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
        }

        public Ingreti() {
        }
    }
}
